version: '3'
services:
    node:
        container_name: node
        image: node:16-alpine
        volumes:
            - .:/var/www/zemoga-challenge
        ports:
            - 3000:3000
        tty: true
        stdin_open: true
