service: serverless-typescript-aws
frameworkVersion: '3'

custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true
    serverless-offline:
        port: 3000

# Add the serverless-webpack plugin
plugins:
    - serverless-webpack
    - serverless-esbuild
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    region: ap-south-1
    profile: serverless-deploy
    apiGateway:
        minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
        shouldStartNameWithService: true
    environment: ${file(env.yml):${opt:stage}}

functions:
    hello:
        handler: handler.hello
        description: Example hello world endpoint
        events:
            - http:
                  method: get
                  path: hello
                  cors: true
